spring:
  application:
    name: kafka-hybrid-rest-lesson12

  # Kafka configuration for Lesson 12 - Kafka-Triggered REST & Command APIs
  kafka:
    bootstrap-servers: localhost:9092
    
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    
    consumer:
      group-id: lesson12-hybrid-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.learning.KafkaStarter.model"
        # Consumer settings for hybrid patterns
        session.timeout.ms: 30000
        heartbeat.interval.ms: 3000
        max.poll.records: 50

server:
  port: 8092

logging:
  level:
    com.learning.KafkaStarter: DEBUG
    org.springframework.kafka: INFO
    org.springframework.web.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,kafka
  endpoint:
    health:
      show-details: always

# Custom configuration for hybrid patterns
hybrid:
  api:
    timeout: 30000
    retries: 3
    retry-delay: 1000
  webhook:
    timeout: 15000
    retries: 2
    retry-delay: 2000