spring:
  application:
    name: kafka-streams-lesson14

  # Kafka configuration for Lesson 14
  kafka:
    bootstrap-servers: localhost:9092
    
    # Producer configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    
    # Consumer configuration  
    consumer:
      group-id: lesson14-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.learning.KafkaStarter.model"
    
    # Kafka Streams configuration
    streams:
      application-id: lesson14-streams-app
      state-dir: /tmp/kafka-streams/lesson14
      replication-factor: 1
      default:
        key:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          serde: org.springframework.kafka.support.serializer.JsonSerde
      properties:
        processing.guarantee: exactly_once_v2
        commit.interval.ms: 1000
        cache.max.bytes.buffering: 1048576  # 1MB
        num.stream.threads: 2

# Server configuration
server:
  port: 8091

# Logging configuration
logging:
  level:
    com.learning.KafkaStarter: DEBUG
    org.apache.kafka.streams: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,kafka
  endpoint:
    health:
      show-details: always