spring:
  application:
    name: kafka-request-reply-lesson13

  # Kafka configuration for Lesson 13 - Request-Reply Patterns
  kafka:
    bootstrap-servers: localhost:9092
    
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    
    consumer:
      group-id: lesson13-request-reply-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.learning.KafkaStarter.model"
        # Consumer settings for request-reply patterns
        session.timeout.ms: 30000
        heartbeat.interval.ms: 3000
        max.poll.records: 10  # Lower for better response times

    # Request-Reply specific configuration
    template:
      default-topic: price-requests
    
server:
  port: 8093

logging:
  level:
    com.learning.KafkaStarter: DEBUG
    org.springframework.kafka: INFO
    org.springframework.kafka.requestreply: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,kafka
  endpoint:
    health:
      show-details: always

# Request-Reply specific configuration
request-reply:
  default-timeout: 30000
  price-service:
    timeout: 15000
    retries: 2
  validation-service:
    timeout: 10000
    retries: 1