spring:
  application:
    name: kafka-manual-ack-lesson9

  # Kafka configuration for Lesson 9 - Manual Acknowledgment & Idempotent Consumers
  kafka:
    bootstrap-servers: localhost:9092
    
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      # Idempotent producer configuration
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        compression.type: snappy
      
    consumer:
      group-id: lesson9-manual-ack-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      # Manual acknowledgment configuration
      enable-auto-commit: false
      # Session and heartbeat configuration for manual ack
      session-timeout-ms: 30000
      heartbeat-interval-ms: 3000
      properties:
        spring.json.trusted.packages: "com.learning.KafkaStarter.model"
        # Exactly-once semantics
        isolation.level: read_committed

server:
  port: 8089

logging:
  level:
    com.learning.KafkaStarter: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,kafka
  endpoint:
    health:
      show-details: always